// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/portworx/px-object-controller/client/clientset/versioned/typed/pxobjectservice/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePxobjectserviceV1alpha1 struct {
	*testing.Fake
}

func (c *FakePxobjectserviceV1alpha1) PXBucketClaims(namespace string) v1alpha1.PXBucketClaimInterface {
	return &FakePXBucketClaims{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePxobjectserviceV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
