// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PXBucketClaimListerExpansion allows custom methods to be added to
// PXBucketClaimLister.
type PXBucketClaimListerExpansion interface{}

// PXBucketClaimNamespaceListerExpansion allows custom methods to be added to
// PXBucketClaimNamespaceLister.
type PXBucketClaimNamespaceListerExpansion interface{}
