---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: px-object-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: px-object-controller
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: px-object-controller
    spec:
      imagePullSecrets:
        - name: pwxbuild
      containers:
        - name: px-object-controller
          image: ggriffiths/px-object-controller:latest
          imagePullPolicy: Always
          env:
          - name: S3_ADMIN_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: px-object-s3-admin-credentials
                  key: access-key-id
          - name: S3_ADMIN_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: px-object-s3-admin-credentials
                  key: secret-access-key
          - name: PURE_FB_ADMIN_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: px-object-fb-admin-credentials
                  key: access-key-id
          - name: PURE_FB_ADMIN_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: px-object-fb-admin-credentials
                  key: secret-access-key
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/osd.openstorage.org
            type: DirectoryOrCreate
    