---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: px-object-controller
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: px-object-controller
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: px-object-controller
    spec:
      imagePullSecrets:
        - name: pwxbuild
      serviceAccount: px-object-controller
      containers:
        - name: px-object-controller
          image: ggriffiths/px-object-controller:latest
          imagePullPolicy: Always
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/osd.openstorage.org
            type: DirectoryOrCreate