---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      imagePullSecrets:
        - name: pwxbuild
      containers:
        - name: sample-app
          image: priyanshu511/pos-sample-app:latest
          imagePullPolicy: Always
          env:
          - name: S3_ACCESS_KEY_1
            valueFrom:
                secretKeyRef:
                  name: px-os-credentials-fb-pba
                  key: access-key-id
          - name: S3_SECRET_KEY_1
            valueFrom:
                secretKeyRef:
                  name: px-os-credentials-fb-pba
                  key: secret-access-key
          - name: S3_BUCKET_NAME_1
            valueFrom:
                secretKeyRef:
                  name: px-os-credentials-fb-pba
                  key: bucket-id
          - name: S3_ACCESS_KEY_2
            valueFrom:
                secretKeyRef:
                  name: px-os-credentials-fb-pba-2
                  key: access-key-id
          - name: S3_SECRET_KEY_2
            valueFrom:
                secretKeyRef:
                  name: px-os-credentials-fb-pba-2
                  key: secret-access-key
          - name: S3_BUCKET_NAME_2
            valueFrom:
                secretKeyRef:
                  name: px-os-credentials-fb-pba-2
                  key: bucket-id
          - name: S3_ENDPOINT
            valueFrom:
                secretKeyRef:
                  name: px-os-credentials-fb-pba
                  key: endpoint
    
