// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/portworx/px-object-controller/client/apis/objectservice/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePXBucketAccesses implements PXBucketAccessInterface
type FakePXBucketAccesses struct {
	Fake *FakeObjectV1alpha1
	ns   string
}

var pxbucketaccessesResource = schema.GroupVersionResource{Group: "object.portworx.io", Version: "v1alpha1", Resource: "pxbucketaccesses"}

var pxbucketaccessesKind = schema.GroupVersionKind{Group: "object.portworx.io", Version: "v1alpha1", Kind: "PXBucketAccess"}

// Get takes name of the pXBucketAccess, and returns the corresponding pXBucketAccess object, and an error if there is any.
func (c *FakePXBucketAccesses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PXBucketAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pxbucketaccessesResource, c.ns, name), &v1alpha1.PXBucketAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PXBucketAccess), err
}

// List takes label and field selectors, and returns the list of PXBucketAccesses that match those selectors.
func (c *FakePXBucketAccesses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PXBucketAccessList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pxbucketaccessesResource, pxbucketaccessesKind, c.ns, opts), &v1alpha1.PXBucketAccessList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PXBucketAccessList{ListMeta: obj.(*v1alpha1.PXBucketAccessList).ListMeta}
	for _, item := range obj.(*v1alpha1.PXBucketAccessList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pXBucketAccesses.
func (c *FakePXBucketAccesses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pxbucketaccessesResource, c.ns, opts))

}

// Create takes the representation of a pXBucketAccess and creates it.  Returns the server's representation of the pXBucketAccess, and an error, if there is any.
func (c *FakePXBucketAccesses) Create(ctx context.Context, pXBucketAccess *v1alpha1.PXBucketAccess, opts v1.CreateOptions) (result *v1alpha1.PXBucketAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pxbucketaccessesResource, c.ns, pXBucketAccess), &v1alpha1.PXBucketAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PXBucketAccess), err
}

// Update takes the representation of a pXBucketAccess and updates it. Returns the server's representation of the pXBucketAccess, and an error, if there is any.
func (c *FakePXBucketAccesses) Update(ctx context.Context, pXBucketAccess *v1alpha1.PXBucketAccess, opts v1.UpdateOptions) (result *v1alpha1.PXBucketAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pxbucketaccessesResource, c.ns, pXBucketAccess), &v1alpha1.PXBucketAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PXBucketAccess), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePXBucketAccesses) UpdateStatus(ctx context.Context, pXBucketAccess *v1alpha1.PXBucketAccess, opts v1.UpdateOptions) (*v1alpha1.PXBucketAccess, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pxbucketaccessesResource, "status", c.ns, pXBucketAccess), &v1alpha1.PXBucketAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PXBucketAccess), err
}

// Delete takes name of the pXBucketAccess and deletes it. Returns an error if one occurs.
func (c *FakePXBucketAccesses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pxbucketaccessesResource, c.ns, name), &v1alpha1.PXBucketAccess{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePXBucketAccesses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pxbucketaccessesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PXBucketAccessList{})
	return err
}

// Patch applies the patch and returns the patched pXBucketAccess.
func (c *FakePXBucketAccesses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PXBucketAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pxbucketaccessesResource, c.ns, name, pt, data, subresources...), &v1alpha1.PXBucketAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PXBucketAccess), err
}
